import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/NavbarPage";
import FooterPage from "./components/footer/FooterPage";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar /> {/* Navbar bileşenini buraya ekleyin */}
        <main>{children}</main> {/* Ana içerik alanı */}
        <FooterPage /> {/* Footer bileşenini buraya ekleyin */}
      </body>
    </html>
  );
}
