import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/page";
import Footer from "./footer/page";
import { NextIntlClientProvider, useMessages } from "next-intl";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Nest.js, Next.js, Medium Alternative Blog App",
  description: "Generated by tariksogukpinar.dev",
};

export default function LocaleLayout({ children, params }) {
  const { locale } = params;
  const messages = useMessages();

  return (
    <html lang={locale}>
      <head>
        <meta name="description" content="Your site description" />
        <meta name="keywords" content="keyword1, keyword2, keyword3" />
        <meta name="robots" content="index, follow" />
      </head>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          <main>{children}</main> {/* Ana içerik alanı */}
          <Footer /> {/* Footer bileşenini buraya ekleyin */}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
